services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    logging:
      driver: loki
      options:
       loki-url: http://localhost:3100/loki/api/v1/push
#        loki-url: http://host.docker.internal:3100/loki/api/v1/push

  grafana:
    image: grafana/grafana:11.3.1
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    ports:
      - "3000:3000"
    depends_on:
      - loki

  loki:
    image: grafana/loki:3.3.1
    ports:
      - "3100:3100"

